SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRACERT04] (
		[IP]            [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[REGID]         [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[HOPE]          [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IPDETAILS]     [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRACERT04] SET (LOCK_ESCALATION = TABLE)
GO
