SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MstPubIPMon_Group] (
		[GrpID]          [bigint] NOT NULL,
		[MemberID]       [bigint] NULL,
		[SiteID]         [bigint] NULL,
		[XmlStr]         [varchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CreatedBy]      [bigint] NULL,
		[UpdatedBy]      [bigint] NULL,
		[DcdTime]        [datetime] NULL,
		[UpDcdTime]      [datetime] NULL,
		[IsEnabled]      [bit] NULL,
		[IsMGMTUser]     [bit] NULL,
		[Reason]         [varchar](2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [Second] TEXTIMAGE_ON [Second]
GO
ALTER TABLE [dbo].[MstPubIPMon_Group]
	ADD
	CONSTRAINT [DF__MstPubIPM__IsMGM__12C8C788]
	DEFAULT ((0)) FOR [IsMGMTUser]
GO
ALTER TABLE [dbo].[MstPubIPMon_Group]
	ADD
	CONSTRAINT [DF_IsEnabled]
	DEFAULT ((1)) FOR [IsEnabled]
GO
ALTER TABLE [dbo].[MstPubIPMon_Group]
	ADD
	CONSTRAINT [DX_DcdTime]
	DEFAULT (getdate()) FOR [DcdTime]
GO
CREATE CLUSTERED INDEX [IX_GrpID]
	ON [dbo].[MstPubIPMon_Group] ([GrpID])
	ON [Second]
GO
EXEC sp_addextendedproperty N'MS_Description', N'Email Id of logged in user', 'SCHEMA', N'dbo', 'TABLE', N'MstPubIPMon_Group', 'COLUMN', N'CreatedBy'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Data center time', 'SCHEMA', N'dbo', 'TABLE', N'MstPubIPMon_Group', 'COLUMN', N'DcdTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Autogenerated Group ID', 'SCHEMA', N'dbo', 'TABLE', N'MstPubIPMon_Group', 'COLUMN', N'GrpID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Member ID', 'SCHEMA', N'dbo', 'TABLE', N'MstPubIPMon_Group', 'COLUMN', N'MemberID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Site ID', 'SCHEMA', N'dbo', 'TABLE', N'MstPubIPMon_Group', 'COLUMN', N'SiteID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Email Id of user who have modified entry', 'SCHEMA', N'dbo', 'TABLE', N'MstPubIPMon_Group', 'COLUMN', N'UpdatedBy'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Updated data center time', 'SCHEMA', N'dbo', 'TABLE', N'MstPubIPMon_Group', 'COLUMN', N'UpDcdTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'All Configured IP''s comes in a form of XML', 'SCHEMA', N'dbo', 'TABLE', N'MstPubIPMon_Group', 'COLUMN', N'XmlStr'
GO
ALTER TABLE [dbo].[MstPubIPMon_Group] SET (LOCK_ESCALATION = TABLE)
GO
