SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TraceRT2] (
		[Col001]     [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[Col002]     [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[Col003]     [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[Col004]     [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TraceRT2] SET (LOCK_ESCALATION = TABLE)
GO
